### ISSUE TITLE
TypeError when Spotify user URLs are matched

### ISSUE THREAD

**Issue by nimuxoha** [Lioncat6/MusicBrainz-UserScripts#4]
The script is expecting Spotify artist URLs only however Spotify user URLs as social network relationship type are allowed.
For example: https://musicbrainz.org/artist/0df563ec-1a79-486e-a46d-5b9862a40311

This leads to an error and the button doesn't appear:
```
Uncaught TypeError: Cannot read properties of null (reading '1')
    at Musicbrainz Artist SAMBL Button.user.js:26:48
    at Musicbrainz Artist SAMBL Button.user.js:39:3
    at VM3xvyvq316nl (Musicbrainz Artist SAMBL Button.user.js:40:3)
    at rn (injected-web.js:1:15907)
    at Musicbrainz Artist SAMBL Button.user.js:1:21
    at async Wt (injected.js:1:8803)
    at async injected.js:1:14545
(anonymous) @ Musicbrainz Artist SAMBL Button.user.js:26
(anonymous) @ Musicbrainz Artist SAMBL Button.user.js:39
VM3xvyvq316nl @ Musicbrainz Artist SAMBL Button.user.js:40
rn @ injected-web.js:1
(anonymous) @ Musicbrainz Artist SAMBL Button.user.js:1
await in (anonymous)
zt @ injected.js:1
Wt @ injected.js:1
await in Wt
(anonymous) @ injected.js:1
await in (anonymous)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
```

**Comment by Lioncat6** [comment]
Fixed!

Side note: the Spotify artist photo of that artist you used as an example is nightmare fuel,
